# frontend v-1 multi-stage build
FROM node:18-alpine AS build

WORKDIR /app

COPY frontend-v1/package*.json ./

RUN npm ci --only=production

COPY frontend-v1/ ./

RUN npm run build

# -----------------------------------------------#

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 9090

CMD ["nginx", "-g", "daemon off;"]